name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name : Checkout Repo
          uses: actions/checkout@v4.2.2

        - name: List and Read New File
          run: |
            echo "my First Github Actions Example"
            ls -ltra
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "run for cover...I am a dragon">> dragon.txt
              
        #- name : List Files
        #  run : ls

        #- name: read files
        #  run: cat README.md 
